App\Entity\Admin:
    attributes:
        normalization_context:
            groups:
                - 'admin:output'
        denormalization_context:
            groups:
                - 'admin:input'