App\Entity\Article:
    attributes:
        normalization_context:
            groups: ['article:output']
        denormalization_context:
            groups: ['article:input']
        hasParts:
            groups:
                - 'article:output'

