App\Entity\Editor:
    attributes:
        normalization_context:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
        denormalization_context:
            groups:
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        emailContact:
            groups:
                - 'article:output'
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        nickname:
            groups:
                - 'article:output'
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        familyName:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        givenName:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        affiliation:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        alumniOf:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        rateGlobal:
            groups:
                - 'article:output'
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'moderator:input'
                - 'admin:input'
        rateContribution:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        sanctioned:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'moderator:input'
                - 'admin:input'
        groupsOwned:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        groupsMember:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        subjectsCreated:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        contributionsMade:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        chatroomsCreated:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        chatroomsInvolved:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        messagesWritten:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        notesSuggested:
            groups:
                - 'article:output'
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        abusesIdentified:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        abusesAccused:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'editor:input'
                - 'moderator:input'
                - 'admin:input'
        sanctionReceived:
            groups:
                - 'editor:output'
                - 'moderator:output'
                - 'admin:output'
                - 'moderator:input'
                - 'admin:input'



