App\Entity\Editor:
    attributes:
        normalization_context:
            groups:
                - 'editor:output'
        denormalization_context:
            groups:
                - 'editor:input'
        nickname:
            groups:
                - 'article:output'


