App\Entity\Grain:
    attributes:
        normalization_context:
            groups:
                - 'subject:output'
                - 'article:output'
        denormalization_context:
            groups:
                - 'subject:input'
        content:
            groups:
                - 'subject:output'
                - 'subject:input'
                - 'article:output'
        dateCreated:
            groups:
                - 'subject:output'
                - 'subject:input'
        dateModified:
            groups:
                - 'subject:output'
                - 'subject:input'
        datePublished:
            groups:
                - 'subject:output'
                - 'subject:input'
        draft:
            groups:
                - 'subject:output'
                - 'subject:input'
        rating:
            groups:
                - 'subject:output'
                - 'subject:input'