App\Entity\Image:
    attributes:
        normalization_context:
            groups: ['image:output','subject:output']
        denormalization_context:
            groups:
                - 'image:input'
        url:
            groups:
                - 'subject:output'
                - 'article:output'
        title:
            groups:
                - 'subject:output'
                - 'article:output'
        alt:
            groups:
                - 'subject:output'
                - 'article:output'