App\Entity\Subject:
    attributes:
        normalization_context:
            groups: ['subject:output']
        denormalization_context:
            groups: ['subject:input']
        images:
            groups: ['article:output']
            #max_depth: 1
        video:
            groups: ['subject:output']
            #max_depth: 1
