App\Entity\User:
    attributes:
        normalization_context:
            groups:
                - 'user:output'
        denormalization_context:
            groups:
                - 'user:input'
