App\Entity\Video:
    attributes:
        normalization_context:
            groups:
                - 'video:output'
        denormalization_context:
            groups:
                - 'video:input'
