# Configuration de l'API par ressource:
App\Entity\Abuse:
    collectionOperations:
        get:
            method: 'GET'
            path: '/abuses'
    itemOperations:
        get:
            method: 'GET'
            path: '/abuse/{id}'

App\Entity\Article:
    # Prefix de route
    routePrefix: '/docs'
    # Configuration des relations
    properties:
        subresource:
            resourceClass: 'App\Entity\Grain'
            collection: true
    # Configuration Opérations
    collectionOperations:
        get:
            method: 'GET'
            path: '/articles'
              #host: {subdomain}.localhost
              #defaults:
              #    color: "brown"
              #schemes: ['https']
              #options:
            #my_option: my_values
            #post:
            #method: 'POST'
            #path: '/articles
            #host: {subdomain}.localhost
            #defaults:
            #   color: "brown"
            #schemes: ['https']
            #options:
            #   my_option: my_values
    itemOperations:
        get:
            method: 'GET'
            path: '/article/{id}'
            requirements:
              id: '\d+'
        post:
            method: 'GET'
            path: '/article/{id}'
            requirements:
              id: '\d+'

App\Entity\Grain:
    collectionOperations:
        # Le nom est important, il sera automatiquement défini à
        # $resources_$subresources_get_subresource
        # Les ressources regroupés
        api_article_grain_get_subresource:
            method: 'GET' # Rien de plus à ajouter si on veut le controller par défaut
            normalization_context: {groups: ['grains']}
    itemOperations:
        get:
            method: 'GET'
            path: '/grain/{id}'
            requirements:
              id: '\d+'
        post:
            method: 'GET'
            path: 'grain/{id}/update'
            requirements:
                id: '\d+'